/**
 * Downloads the Mukta Malar subsets the app uses and writes a local
 * stylesheet for them. Run with `npm run fonts` when the font changes;
 * the .woff2 files are committed so the build never touches the network.
 */
import { writeFile, mkdir } from 'node:fs/promises';

const FAMILY = 'Mukta+Malar:wght@400;600;700';
const WANTED_SUBSETS = new Set(['tamil', 'latin']);
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36';

const css = await (
  await fetch(`https://fonts.googleapis.com/css2?family=${FAMILY}&display=swap`, {
    headers: { 'User-Agent': UA },
  })
).text();

await mkdir('public/fonts', { recursive: true });

// Google emits a `/* subset */` comment before each @font-face block.
const commented = css.split(/\/\*\s*([\w-]+)\s*\*\//).slice(1);
for (let i = 0; i < commented.length; i += 2) {
  const name = commented[i];
  const block = commented[i + 1];
  if (!WANTED_SUBSETS.has(name)) continue;
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
  const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  const range = block.match(/unicode-range:\s*([^;]+);/)?.[1];
  if (!weight || !url) continue;

  const file = `mukta-malar-${weight}-${name}.woff2`;
  const bytes = Buffer.from(await (await fetch(url)).arrayBuffer());
  await writeFile(`public/fonts/${file}`, bytes);
  console.log(file.padEnd(34), (bytes.length / 1024).toFixed(1), 'KB');

  rules.push(
    [
      '@font-face {',
      "  font-family: 'Mukta Malar';",
      '  font-style: normal;',
      `  font-weight: ${weight};`,
      '  font-display: swap;',
      `  src: url('/fonts/${file}') format('woff2');`,
      range ? `  unicode-range: ${range};` : null,
      '}',
    ]
      .filter(Boolean)
      .join('\n'),
  );
}

await writeFile(
  'src/fonts.css',
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n${rules.join('\n\n')}\n`,
  'utf8',
);
console.log(`\nwrote src/fonts.css with ${rules.length} faces`);
