/**
 * Writes src/app/core/version.ts from package.json and git, so the running app
 * can say which build it is. Runs as the first step of `npm run build`.
 *
 * The generated file is committed, so `npm start` and the tests work without
 * running this first; the build overwrites it with current values.
 */
import { execFileSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';

const { version } = JSON.parse(await readFile('package.json', 'utf8'));

const git = (...args) => {
  try {
    return execFileSync('git', args, { encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
};

const commit = git('rev-parse', '--short', 'HEAD') || 'local';
const built = new Date().toISOString().slice(0, 10);

const file = `/**
 * Generated by scripts/generate-version.mjs — do not edit by hand.
 * Regenerated on every production build.
 */
export const APP_VERSION = '${version}';
export const APP_COMMIT = '${commit}';
export const APP_BUILT_ON = '${built}';
`;

await writeFile('src/app/core/version.ts', file, 'utf8');
console.log(`version.ts: ${version} (${commit}) built ${built}`);
