/**
 * Generated by scripts/generate-version.mjs — do not edit by hand.
 * Regenerated on every production build.
 */
export const APP_VERSION = '1.0.0';
export const APP_COMMIT = '97ca81f';
export const APP_BUILT_ON = '2026-09-20';
