/**
 * Generated by scripts/generate-version.mjs — do not edit by hand.
 * Regenerated on every production build.
 */
export const APP_VERSION = '1.0.1';
export const APP_COMMIT = 'ac71d7d';
export const APP_BUILT_ON = '2026-09-27';
